# StatefulSet profile for Lab 15.
# Usage:
# helm upgrade --install devops-stateful k8s/devops-info-service -n lab15 -f k8s/devops-info-service/values-statefulset.yaml

replicaCount: 3

service:
  type: ClusterIP
  port: 80
  targetPort: 5001

rollout:
  enabled: false

statefulset:
  enabled: true
  podManagementPolicy: OrderedReady
  headlessServiceSuffix: headless

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 100Mi
  storageClass: ""
