apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-info-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/plaffyyy/DevOps-Core-Course.git
    targetRevision: labs/lab12
    path: k8s/devops-info-service
    helm:
      valueFiles:
        - values-dev.yaml
      valuesObject:
        service:
          type: ClusterIP
      releaseName: devops-info-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
